In [19]:
"""1) Create an empty dictionary and fill with some book_id and book_name as pair by user input. 
Then take one book_id as input from the user and traverse through dictionary to find the corresponding 
book_name and display the same."""

books = {}

n = int(input("Enter the number of books you want to store: "))
print()

for i in range(n):
    book_id = input("Enter the book id: ")
    book_name = input("Enter the book name: ")
    
    books[book_id.title()] = book_name

print("\nStored Books\n")
print(books)

book_to_search = input("Enter the book ID you want to search: ")

if book_to_search in books:
    print("Book Found! Book Name: ", books[book_to_search])

else:
    print("Book NOT Found!!!")

Enter the number of books you want to store: 3

Enter the book id: 1
Enter the book name: ruban
Enter the book id: 2
Enter the book name: gino
Enter the book id: 3
Enter the book name: singh

Stored Books

{'1': 'ruban', '2': 'gino', '3': 'singh'}
Enter the book ID you want to search: 2
Book Found! Book Name:  gino


In [28]:
"""2) Create an empty list and fill with list of strings by user input.
Find the number of strings where the string length is 2 or more and the first and 
last character are same. 

Sample List: ['abc', 'xyz', 'aba', '1221']

Expected Result: 2"""

n = int(input("Enter the number of values: "))

list = []

for i in range(n): 
    list.append(input())

count = 0
for i in list: 
    if len(i)>2 and i[0]==i[-4]: 
        count += 1

print("Number of strings with same character: ", count)

Enter the number of values: 3
ab
abca
a
Number of strings with same character:  1


In [31]:
"""3) Create an empty set and fill with some values by user input. find maximum value in a set."""

set_to_store = set() 

num = int(input("Enter the number of values: "))

for i in range(num):
    set_to_store.add(int(input()))
print("Maximum value is: ", max(set_to_store))

Enter the number of values: 5
6
4
7
5
2
Maximum value is:  7


In [32]:
"""4) Create an empty tuple and fill with some values by user input. Find the sum of tuple elements."""

user_input = tuple(map(int, input( 'Enter some values seperated by space: ').split()))
sum = 0

for element in user_input:
    sum = sum + element

print("Sum of tuple elements", user_input, "=", sum)

Enter some values seperated by space: 1 2 3 4 5
Sum of tuple elements (1, 2, 3, 4, 5) = 15


In [34]:
"""5) Create a 2D array and perform matrix addition using numpy."""

import numpy as np

first_value = np.array([[1,2,3],[2,3,4],[3,4,5]])
second_value = np.array([[7,9,5],[3,6,4],[6,4,7]])

addition = first_value + second_value

print("The Addition Values of the Given Matrix is: ")
print(addition)


The Addition Values of the Given Matrix is: 
[[ 8 11  8]
 [ 5  9  8]
 [ 9  8 12]]


In [36]:
"""6) Read an .csv file and display the basic details"""

import pandas as pd

data_frame = pd.read_csv('heart.csv')

print(data_frame)

     Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope  Ca        Thal  AHD  
0        0   